// Request translation: Anthropic → OpenAI Responses API

import type { AnthropicRequest, AnthropicMessage, AnthropicToolResultBlock, AnthropicSystemBlock } from '../types/anthropic';
import type { ResponsesRequest, ResponsesInputItem, ResponsesInputContentPart, ResponsesInputFunctionCall, ResponsesToolChoice } from '../types/openai-responses';
import type { BridgeConfig } from '../types/bridge';
import type { ToolImageSaver } from './multimodal';
import { stripModelSuffix } from '../../../shared/contextUsage';


export interface TranslateRequestResponsesOptions {
  modelMapping?: BridgeConfig['modelMapping'];
  modelOverride?: string;
  imageSaver?: ToolImageSaver;
  /** #324 — user-selected reasoning effort (NORMALIZED level). Injected as
   *  `reasoning: { effort }`; absent = field omitted entirely. */
  reasoningEffort?: string;
  /** Stable cache-affinity key generated by the bridge. Never user-authored. */
  promptCacheKey?: string;
}

/** Translate Anthropic Messages API request → OpenAI Responses API request */
export function translateRequestToResponses(
  req: AnthropicRequest,
  options?: TranslateRequestResponsesOptions,
): ResponsesRequest {
  // 1. Model mapping
  let model = req.model;
  if (options?.modelOverride) {
    model = options.modelOverride;
  } else if (options?.modelMapping) {
    const mapping = options.modelMapping;
    if (typeof mapping === 'function') {
      model = mapping(req.model) ?? req.model;
    } else {
      model = mapping[req.model] ?? req.model;
    }
  }
  // SDK-ingress-only: strip the `[1m]` / ` 1m` capability decoration before the
  // wire (#338) — same rationale as the Chat Completions translator. Config-fed
  // modelOverride / modelMapping can carry a stored suffix the upstream rejects.
  model = stripModelSuffix(model) ?? model;

  // 2. System prompt — folded into input[0] instead of `instructions`
  //
  // #325 — strict proxies (Rust serde untagged enum — agnes, etc.) reject the
  // `instructions` field in EVERY form we tried:
  //   - bare string `instructions: "<text>"`  → untagged enum ResponseInput at line 1 col N (mid-string)
  //   - array       `instructions: [{type:'message',role:'system',content:'<text>'}]` → same error, +30 bytes shift
  // agnes's ResponsesRequest schema appears to have `instructions: Never` (or
  // a narrower type we can't satisfy). Workaround: prepend the Anthropic
  // `system` block to the input array as a role:'system' message. OpenAI
  // Responses API accepts this — `input[0]` can be any ResponseInputItem,
  // and role:'system' is valid per EasyInputMessageParam. Lenient providers
  // (OpenAI official) treat the system role identically to instructions.
  //
  // ponytail: if a strict proxy later accepts `instructions: str` exactly,
  // revert this and emit a bare string. If `instructions: ResponseInput[]`
  // ever starts working (fix #6 shape), revert. Until then, input prepend is
  // the only known-good shape across both lenient and strict providers.
  const systemMessage: ResponsesInputItem[] = req.system
    ? [
        {
          type: 'message',
          role: 'system',
          content:
            typeof req.system === 'string'
              ? req.system
              : (req.system as AnthropicSystemBlock[]).map((b) => b.text).join('\n\n'),
        },
      ]
    : [];

  // 3. Input messages
  const input = translateMessagesToResponses(req.messages, options?.imageSaver);

  // 4. Build request
  // NOTE: max_output_tokens, temperature, top_p are intentionally NOT forwarded.
  // - max_output_tokens: handler injects user-configured cap via the correct param name.
  // - temperature, top_p: SDK values may not be compatible with target model. Let upstream use defaults.
  const responsesReq: ResponsesRequest = {
    model,
    input: [...systemMessage, ...input],
  };

  if (options?.promptCacheKey) responsesReq.prompt_cache_key = options.promptCacheKey;

  // 5. Tools
  // Function-tool fields are nested under `function:` — matches OpenAI's
  // documented FunctionToolParam shape and `tools.ts::translateToolDefinitions`
  // (chat-completions path). Strict untagged-enum deserializers (Rust serde
  // — agnes) reject the flat shape with `Function tool must have a function
  // definition` and then give up inside a long tool description string with
  // `untagged enum ResponseInput at line 1 column N` (column 63453 fell
  // inside EnterPlanMode.description in the 2026-09-20 regression — 115KB
  // request body, 26 tools). OpenAI official / xAI / other lenient
  // providers accept both shapes; the nested form is the documented one.
  //
  // ponytail: #325 — `strict` is `Required[Optional[bool]]` per OpenAI spec;
  // strict proxies dispatch the FunctionToolParam variant only when it is
  // present. We always emit `strict: false` (the historical default; newer
  // OpenAI tools prefer `strict: true` with strict JSON-schema subsets, but
  // flipping every Anthropic tool to strict mode is a separate, larger
  // conversation — see `Models` providers' "JSON-schema subset compliance"
  // docs). Lenient clients accept omission; emitting it costs nothing and
  // saves strict providers from a 400.
  //
  // #325 — agnes's strict deserializer also chokes on long `description`
  // strings inside tool `parameters` JSON-schema (column 45371 fell inside
  // the AskUserQuestion option.preview.description text). Symptom is the
  // same `untagged enum ResponseInput at line 1 column N` — agnes appears
  // to walk every long string in the body looking for ResponseInput
  // variants and reports the offset where it gives up. Stripping
  // property-level `description` fields from tool schemas is harmless
  // (the LLM still gets the tool's top-level `description` and `name` and
  // the property `type` — enough to understand the tool). Kept the
  // tool's top-level `description` (function description, not schema
  // description) because that's how the LLM learns what the tool does.
  if (req.tools && req.tools.length > 0) {
    responsesReq.tools = req.tools.map(t => ({
      type: 'function' as const,
      function: {
        name: t.name,
        description: t.description,
        // JSON Schema tool parameters are always an object at the top level;
        // the array branch of `stripSchemaDescriptions` only fires for nested
        // positions (properties[].items / oneOf / anyOf / allOf), so the cast
        // is sound.
        parameters: stripSchemaDescriptions(t.input_schema) as Record<string, unknown> | undefined,
        strict: false,
      },
    }));
  }

  // 6. Tool choice
  if (req.tool_choice) {
    responsesReq.tool_choice = translateToolChoiceToResponses(req.tool_choice);
  }

  // 7. Stream
  if (req.stream) {
    responsesReq.stream = true;
  }

  // 8. Reasoning effort (#324): forwarded ONLY when the user explicitly
  // selected a non-default effort AND the value is in the Responses-safe
  // vocabulary. Same omit-by-default rationale as the Chat Completions
  // translator (unknown args → 400 on strict providers). Responses API's
  // documented effort enum is the strict 4-value set below; Claude-only
  // tiers (`max`) and OpenAI extensions outside it (`xhigh`) are silently
  // omitted rather than remapped, because remapping can mask the user's
  // intent (`max` thinking ≠ `high` thinking) and stricter proxies
  // (Rust serde with untagged enum — agnes, etc.) reject unknown
  // variants at deserialization time with 400 json_parse_error.
  // Regression: agnes-2.5-flash chat surfaced `effort: unknown variant
  // max, expected one of minimal, low, medium, high` after the previous
  // output_text fix unblocked earlier parsing. The xai-sub Grok whitelist
  // in `shouldSendProviderReasoningEffort` runs in the handler gate
  // BEFORE this translator, but its allowed set is a subset of the
  // Responses-safe set so the gate remains a no-op for Grok here.
  // ponytail: extend with `xhigh` once an OpenAI-compatible provider
  // surfaced in production accepts it (Responses spec lists it but
  // every strict proxy we've seen rejects it).
  const RESPONSES_EFFORT_VALUES = new Set(['minimal', 'low', 'medium', 'high']);
  if (options?.reasoningEffort && RESPONSES_EFFORT_VALUES.has(options.reasoningEffort)) {
    responsesReq.reasoning = { effort: options.reasoningEffort };
  }

  return responsesReq;
}

function translateToolChoiceToResponses(choice: NonNullable<AnthropicRequest['tool_choice']>): ResponsesToolChoice {
  switch (choice.type) {
    case 'auto': return 'auto';
    case 'any': return 'required';
    case 'none': return 'none';
    case 'tool': return { type: 'function', name: choice.name };
  }
}

function translateMessagesToResponses(messages: AnthropicMessage[], imageSaver?: ToolImageSaver): ResponsesInputItem[] {
  const result: ResponsesInputItem[] = [];

  // Collect known tool_use_ids for orphan detection
  const knownToolUseIds = new Set<string>();
  for (const msg of messages) {
    if (msg.role === 'assistant' && Array.isArray(msg.content)) {
      for (const block of msg.content) {
        if (block.type === 'tool_use') {
          knownToolUseIds.add(block.id);
        }
      }
    }
  }

  for (const msg of messages) {
    if (msg.role === 'user') {
      translateUserMessageToResponses(msg, result, knownToolUseIds, imageSaver);
    } else if (msg.role === 'assistant') {
      translateAssistantMessageToResponses(msg, result);
    }
  }

  // ponytail: this discriminator is unconditional, but if we ever need to
  // forward provider-specific Responses shapes (MCP tool calls, reasoning
  // replay items, file-search outputs, etc.) we will branch here rather than
  // add a sibling type without discriminator — strict proxies would still
  // reject those variants for the same reason.
  for (const item of result) {
    if ('role' in item) {
      item.type = 'message';
    }
  }

  return result;
}

function translateUserMessageToResponses(
  msg: AnthropicMessage,
  result: ResponsesInputItem[],
  knownToolUseIds: Set<string>,
  imageSaver?: ToolImageSaver,
): void {
  if (typeof msg.content === 'string') {
    result.push({ role: 'user', content: msg.content });
    return;
  }

  const toolResults: AnthropicToolResultBlock[] = [];
  const orphanTexts: string[] = [];
  const otherParts: ResponsesInputContentPart[] = [];

  for (const block of msg.content) {
    if (block.type === 'tool_result') {
      if (knownToolUseIds.has(block.tool_use_id)) {
        toolResults.push(block);
      } else {
        const content = extractToolResultText(block, imageSaver);
        if (content) orphanTexts.push(`[Previous tool result]:\n${content}`);
      }
    } else if (block.type === 'text') {
      otherParts.push({ type: 'input_text', text: block.text });
    } else if (block.type === 'image') {
      if (block.source.type === 'url' && block.source.url) {
        otherParts.push({ type: 'input_image', image_url: block.source.url });
      } else if (block.source.data) {
        const mediaType = block.source.media_type || 'image/png';
        otherParts.push({ type: 'input_image', image_url: `data:${mediaType};base64,${block.source.data}` });
      }
    }
    // thinking blocks filtered
  }

  // Emit function_call_output items for tool results
  for (const tr of toolResults) {
    result.push({
      type: 'function_call_output',
      call_id: tr.tool_use_id,
      output: extractToolResultText(tr, imageSaver),
    });
  }

  // Add orphan text to other parts
  for (const text of orphanTexts) {
    otherParts.push({ type: 'input_text', text });
  }

  // Emit user message for remaining content
  if (otherParts.length > 0) {
    if (otherParts.length === 1 && otherParts[0].type === 'input_text') {
      result.push({ role: 'user', content: otherParts[0].text });
    } else {
      result.push({ role: 'user', content: otherParts });
    }
  }
}

function translateAssistantMessageToResponses(msg: AnthropicMessage, result: ResponsesInputItem[]): void {
  if (typeof msg.content === 'string') {
    result.push({ role: 'assistant', content: msg.content });
    return;
  }

  // Build assistant content parts and function calls
  const contentParts: ResponsesInputContentPart[] = [];
  const functionCalls: ResponsesInputFunctionCall[] = [];

  for (const block of msg.content) {
    if (block.type === 'text') {
      // Assistant text replay MUST use `input_text` — Responses API's
      // `EasyInputMessage::content` rejects `output_text` (which belongs to
      // `ResponsesOutputContent`). Hard failure mode is upstream 400
      // "data did not match any variant of untagged enum ResponseInput"
      // (agnes / Rust serde) once the request body crosses the proxy's
      // lenient-fallthrough threshold. See request-responses.unit.test.ts
      // for the invariant this preserves.
      contentParts.push({ type: 'input_text', text: block.text });
    } else if (block.type === 'tool_use') {
      // In Responses API input replay, function calls are separate items
      functionCalls.push({
        type: 'function_call',
        call_id: block.id,
        name: block.name,
        arguments: typeof block.input === 'string' ? block.input : JSON.stringify(block.input),
      });
    }
    // thinking blocks are not replayed in input
  }

  // Emit text content as assistant message
  if (contentParts.length > 0) {
    result.push({ role: 'assistant', content: contentParts });
  }

  // Emit each function call as a separate input item
  for (const fc of functionCalls) {
    result.push(fc);
  }

  // If no content and no function calls, emit empty assistant message
  if (contentParts.length === 0 && functionCalls.length === 0) {
    result.push({ role: 'assistant', content: '' });
  }
}

function extractToolResultText(tr: AnthropicToolResultBlock, imageSaver?: ToolImageSaver): string {
  const isError = tr.is_error === true;
  if (!tr.content) return isError ? '<error></error>' : '';

  let text: string;
  if (typeof tr.content === 'string') {
    text = tr.content;
  } else {
    const parts: string[] = [];
    for (const c of tr.content) {
      if (c.type === 'text') {
        parts.push(c.text);
      } else if (c.type === 'image') {
        if (imageSaver && c.source?.data) {
          try {
            const relPath = imageSaver(c.source.data, c.source.media_type || 'image/png');
            parts.push(`[Tool returned an image, saved to ${relPath}]`);
          } catch {
            parts.push('[Tool returned an image, failed to save]');
          }
        } else {
          parts.push('[Image content omitted - tool returned an image]');
        }
      }
    }
    text = parts.join('\n');
  }

  return isError ? `<error>${text}</error>` : text;
}

/**
 * Recursively strip `description` fields from a JSON Schema for tool
 * parameters. Keeps `type`, `properties`, `required`, `items`, `enum`,
 * `additionalProperties`, `oneOf`/`anyOf`/`allOf`, etc. — everything the
 * LLM needs to understand the tool's argument shape. Drops STRING-valued
 * `description` fields because some strict Responses-API proxies (Rust
 * serde untagged-enum — agnes) walk long description strings looking for
 * ResponseInput variants and report `untagged enum ResponseInput at line
 * 1 column N` mid-string (regression column 45371 inside AskUserQuestion
 * .preview.description).
 *
 * Important: only strip `description` keys whose VALUE is a string. When
 * value is an object/array (e.g. `description: { type: 'string',
 * description: '…' }` where `description` is itself the *property name*
 * being defined as a string-typed argument — AskUserQuestion's `options
 * [].description`), the value is a legitimate property schema and MUST
 * be preserved. Stripping it drops the argument definition entirely
 * (regression surfaced as agnes 400 at column 45371 — body length 115 KB,
 * 26 tools, the dropped `description` property is the one whose stripped
 * sub-schema sat at that byte offset).
 *
 * ponytail: if a strict proxy later accepts descriptions verbatim, revert
 * this and the caller to pass `t.input_schema` directly. The function
 * remains exported (`stripSchemaDescriptions`) for unit testing only —
 * the translator inlines the call so the JSON tree is walked once.
 */
export function stripSchemaDescriptions(schema: unknown): Record<string, unknown> | unknown[] | undefined {
  if (schema === undefined || schema === null) return undefined;
  if (Array.isArray(schema)) {
    return schema.map(stripSchemaDescriptions);
  }
  if (typeof schema === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(schema as Record<string, unknown>)) {
      // Drop only string-valued `description` (schema annotation). Object-
      // valued `description` is a property definition; keep and recurse so
      // any nested string `description`s inside it still get stripped.
      if (k === 'description' && typeof v === 'string') continue;
      const stripped = stripSchemaDescriptions(v);
      if (stripped !== undefined) out[k] = stripped;
    }
    return out;
  }
  // Scalars pass through unchanged — JSON Schema tool params never have
  // bare scalars at the top level, but a nested `default: 42` / `default: 'x'`
  // / `default: true` value can reach here via the recursive walk. Cast
  // narrows `unknown` to the declared return type without runtime cost.
  return schema as Record<string, unknown> | unknown[];
}
