import { existsSync, lstatSync, readFileSync, realpathSync, statSync, writeFileSync } from 'fs';
import { homedir, tmpdir } from 'os';
import { isAbsolute, join, relative, resolve } from 'path';

import {
  CODEX_SUBSCRIPTION_PROVIDER_ID,
  MANAGED_CODEX_REQUIRED_RUNTIME,
  isCanonicalManagedCodexRuntimeVersion,
} from '../../shared/config-types';
import type { RuntimeEnvPolicy, RuntimeSource } from '../../shared/types/runtime';
import { ensureDirSync } from '../utils/fs-utils';
import { applyProviderProxyPolicyToEnv } from '../proxy-state';
import { augmentedProcessEnv, resolveCommand } from './env-utils';

export interface CodexCommandContext {
  source: RuntimeSource;
  commandPath: string;
  env: Record<string, string | undefined>;
  codexHome?: string;
  version?: string;
  platform?: string;
}

interface ManagedCodexInstalledJson {
  version?: string;
  platform?: string;
  manifestSignature?: string;
  artifactSignatureVerified?: boolean;
  platformSignature?: {
    type?: string;
    teamId?: string;
    certificateSha256?: string;
  };
  executableRelativePath?: string;
}

const PROXY_ENV_KEYS = [
  'HTTP_PROXY',
  'HTTPS_PROXY',
  'ALL_PROXY',
  'NO_PROXY',
  'http_proxy',
  'https_proxy',
  'all_proxy',
  'no_proxy',
] as const;

const MANAGED_SAFE_ENV_KEYS = [
  'PATH',
  'Path',
  'HOME',
  'USERPROFILE',
  'USER',
  'USERNAME',
  'TMPDIR',
  'TEMP',
  'TMP',
  'SystemRoot',
  'WINDIR',
  'ComSpec',
  'PATHEXT',
  'APPDATA',
  'LOCALAPPDATA',
  'LANG',
  'LC_ALL',
  'LC_CTYPE',
  'SSL_CERT_FILE',
  'SSL_CERT_DIR',
  'NODE_EXTRA_CA_CERTS',
  // Non-secret HamunaAgent control-plane env. Managed Codex still gets an
  // isolated CODEX_HOME and no provider auth env, but its shell tool must be
  // able to run the HamunaAgent CLI just like builtin/external runtime shells.
  'HAMUNA_PORT',
  'HAMUNA_MANAGEMENT_PORT',
  'HAMUNA_VERSION',
  'HAMUNA_PROXY_INJECTED',
  ...PROXY_ENV_KEYS,
] as const;

const AUTH_ENV_PREFIXES = [
  'OPENAI_',
  'ANTHROPIC_',
  'GOOGLE_',
  'GEMINI_',
  'DEEPSEEK_',
  'MOONSHOT_',
  'MISTRAL_',
  'XAI_',
  'GROQ_',
  'DASHSCOPE_',
  'ARK_',
  'VOLCENGINE_',
  'AWS_',
  'AZURE_',
  'CLAUDE_',
  'CODEX_',
] as const;

const AUTH_ENV_NAMES = new Set([
  'API_KEY',
  'AUTH_TOKEN',
  'ACCESS_TOKEN',
  'REFRESH_TOKEN',
  'BEARER_TOKEN',
  'TOKEN',
]);

function managedCodexPlatform(): string | null {
  if (process.platform === 'darwin') {
    if (process.arch === 'arm64') return 'darwin-arm64';
    if (process.arch === 'x64') return 'darwin-x64';
    return null;
  }
  if (process.platform === 'win32') {
    if (process.arch === 'x64') return 'win32-x64';
    return null;
  }
  return null;
}

export function getManagedCodexHome(): string {
  return join(homedir(), '.hamuna', 'codex');
}

function getHamunaAgentCliExecutablePath(): string {
  return join(homedir(), '.hamuna', 'bin', process.platform === 'win32' ? 'hamuna.cmd' : 'hamuna');
}

function codexRuleString(value: string): string {
  return JSON.stringify(value);
}

function codexPrefixRule(pattern: string[]): string {
  return `prefix_rule(pattern=[${pattern.map(codexRuleString).join(', ')}], decision="allow")`;
}

export function buildManagedCodexRulesContent(): string {
  const cliPath = getHamunaAgentCliExecutablePath();
  const patterns: string[][] = [
    ['hamuna'],
    ['hamuna.cmd'],
    [cliPath],
    ['/bin/zsh', '-lc', 'hamuna'],
    ['/bin/zsh', '-lc', cliPath],
    ['/bin/bash', '-lc', 'hamuna'],
    ['/bin/bash', '-lc', cliPath],
    ['zsh', '-lc', 'hamuna'],
    ['bash', '-lc', 'hamuna'],
    ['cmd.exe', '/d', '/s', '/c', 'hamuna'],
    ['powershell', '-Command', 'hamuna'],
    ['pwsh', '-Command', 'hamuna'],
  ];
  return [
    '# Generated by HamunaAgent. Do not edit; it is refreshed when managed Codex starts.',
    '# Allows the built-in HamunaAgent CLI control-plane tool to run without sandbox approval.',
    ...patterns.map(codexPrefixRule),
    '',
  ].join('\n');
}

export function ensureManagedCodexRules(): void {
  const rulesDir = join(getManagedCodexHome(), 'rules');
  ensureDirSync(rulesDir);
  const rulesPath = join(rulesDir, 'hamuna.rules');
  const content = buildManagedCodexRulesContent();
  try {
    if (existsSync(rulesPath) && readFileSync(rulesPath, 'utf-8') === content) return;
  } catch {
    // Fall through and rewrite; a broken generated rules file should self-heal.
  }
  writeFileSync(rulesPath, content, 'utf-8');
}

export function getManagedCodexRuntimeRoot(): string {
  return join(homedir(), '.hamuna', 'runtimes', 'codex');
}

function managedCodexInstallDir(platform: string, version = MANAGED_CODEX_REQUIRED_RUNTIME.version): string {
  if (!isCanonicalManagedCodexRuntimeVersion(version)) {
    throw new Error(`Invalid Managed Codex installed version: ${String(version)}`);
  }
  const root = resolve(getManagedCodexRuntimeRoot());
  const installDir = resolve(root, version, platform);
  const rel = relative(root, installDir);
  if (!rel || rel === '..' || rel.startsWith(`..${process.platform === 'win32' ? '\\' : '/'}`) || isAbsolute(rel)) {
    throw new Error(`Managed Codex install directory escapes runtime root: ${installDir}`);
  }
  return installDir;
}

function managedCodexInstalledJsonPath(): string {
  return join(getManagedCodexRuntimeRoot(), 'installed.json');
}

function isExecutableFileWithinRuntime(path: string): boolean {
  try {
    if (!statSync(path).isFile() || lstatSync(path).isSymbolicLink()) return false;
    const realRoot = realpathSync(getManagedCodexRuntimeRoot());
    const realPath = realpathSync(path);
    const rel = relative(realRoot, realPath);
    return Boolean(rel)
      && rel !== '..'
      && !rel.startsWith(`..${process.platform === 'win32' ? '\\' : '/'}`)
      && !isAbsolute(rel);
  } catch {
    return false;
  }
}

function readManagedCodexInstalledJson(): ManagedCodexInstalledJson | null {
  try {
    return JSON.parse(readFileSync(managedCodexInstalledJsonPath(), 'utf8')) as ManagedCodexInstalledJson;
  } catch {
    return null;
  }
}

function safeManagedCodexRelativePath(raw: string | undefined): string | null {
  if (!raw || raw.includes('\0') || raw.includes('\\') || raw.startsWith('/')) return null;
  if (/^[a-zA-Z]:/.test(raw)) return null;
  const segments = raw.split('/');
  if (segments.length === 0 || segments.length > 64) return null;
  for (const segment of segments) {
    if (!segment || segment === '.' || segment === '..' || segment.includes(':')) return null;
    if (/[ .]$/.test(segment)) return null;
  }
  return join(...segments);
}

function safeManagedCodexInstalledRelativePath(raw: string | undefined): string | null {
  const normalized = safeManagedCodexRelativePath(raw);
  if (normalized) return normalized;
  if (process.platform !== 'win32' || !raw?.includes('\\')) return null;
  return safeManagedCodexRelativePath(raw.replace(/\\/g, '/'));
}

export function resolveManagedCodexCommandPath(): string {
  return resolveManagedCodexInstallation().commandPath;
}

function hasVerifiedManagedCodexMetadata(
  installed: ManagedCodexInstalledJson,
  platform: string,
): boolean {
  if (!installed.manifestSignature?.trim() || installed.artifactSignatureVerified !== true) {
    return false;
  }
  const signing = installed.platformSignature;
  if (platform.startsWith('darwin-')) {
    return signing?.type === 'codesign' && Boolean(signing.teamId?.trim());
  }
  if (platform === 'win32-x64') {
    return signing?.type === 'authenticode'
      && /^[0-9a-f]{64}$/i.test(signing.certificateSha256 ?? '');
  }
  return false;
}

function managedCodexBinaryCandidates(installDir: string): string[] {
  return process.platform === 'win32'
    ? [
        join(installDir, 'codex.exe'),
        join(installDir, 'codex.cmd'),
        join(installDir, 'bin', 'codex.exe'),
        join(installDir, 'bin', 'codex.cmd'),
      ]
    : [
        join(installDir, 'codex'),
        join(installDir, 'bin', 'codex'),
      ];
}

function resolveManagedCodexInstallation(): { commandPath: string; version: string } {
  const platform = managedCodexPlatform();
  if (!platform) {
    throw new Error(`Managed Codex is not supported on ${process.platform}-${process.arch}`);
  }

  const installed = readManagedCodexInstalledJson();
  const installedVersion = installed?.version;
  const canUseInstalledVersion = isCanonicalManagedCodexRuntimeVersion(installedVersion)
    && installed?.platform === platform
    && hasVerifiedManagedCodexMetadata(installed, platform);
  if (canUseInstalledVersion) {
    const installDir = managedCodexInstallDir(platform, installedVersion);
    const rel = safeManagedCodexInstalledRelativePath(installed.executableRelativePath);
    if (rel) {
      const commandPath = join(installDir, rel);
      if (isExecutableFileWithinRuntime(commandPath)) return { commandPath, version: installedVersion };
    }
    const commandPath = managedCodexBinaryCandidates(installDir).find(isExecutableFileWithinRuntime);
    if (commandPath) return { commandPath, version: installedVersion };
  }
  throw new Error(
    `Managed Codex runtime is not installed with verified metadata for ${platform}`,
  );
}

function looksLikeAuthEnvName(name: string): boolean {
  const upper = name.toUpperCase();
  if (AUTH_ENV_NAMES.has(upper)) return true;
  if (AUTH_ENV_PREFIXES.some(prefix => upper.startsWith(prefix))) return true;
  return /(API|AUTH|ACCESS|REFRESH|BEARER).*?(KEY|TOKEN|SECRET|PASSWORD)/.test(upper)
    || /(KEY|TOKEN|SECRET|PASSWORD)$/.test(upper);
}

function buildManagedCodexEnv(
  policy?: RuntimeEnvPolicy,
): Record<string, string | undefined> {
  const base = augmentedProcessEnv(policy);
  const env: Record<string, string | undefined> = {};

  for (const key of MANAGED_SAFE_ENV_KEYS) {
    const value = base[key];
    if (value !== undefined) env[key] = value;
  }

  // Defense-in-depth: the allow-list above intentionally omits provider auth,
  // but keep an explicit scrub so future safe-key additions cannot accidentally
  // leak credentials into the managed Codex process.
  for (const key of Object.keys(env)) {
    if (looksLikeAuthEnvName(key)) delete env[key];
  }
  applyProviderProxyPolicyToEnv(env, CODEX_SUBSCRIPTION_PROVIDER_ID);

  const managedHome = getManagedCodexHome();
  ensureDirSync(managedHome);
  ensureDirSync(join(managedHome, 'logs'));
  ensureDirSync(join(managedHome, 'sessions'));
  ensureDirSync(join(managedHome, 'hamuna'));
  ensureManagedCodexRules();

  env.CODEX_HOME = managedHome;
  env.HOME = env.HOME || homedir();
  if (process.platform === 'win32') {
    env.USERPROFILE = env.USERPROFILE || homedir();
    env.TEMP = env.TEMP || tmpdir();
    env.TMP = env.TMP || tmpdir();
  } else {
    env.TMPDIR = env.TMPDIR || tmpdir();
  }
  env.HAMUNA_RUNTIME_SOURCE = 'managed-provider';
  return env;
}

export function resolveCodexCommandContext(args: {
  source?: RuntimeSource;
  envPolicy?: RuntimeEnvPolicy;
} = {}): CodexCommandContext {
  const source = args.source ?? 'system-cli';
  if (source === 'managed-provider') {
    const platform = managedCodexPlatform();
    const installation = resolveManagedCodexInstallation();
    return {
      source,
      commandPath: installation.commandPath,
      env: buildManagedCodexEnv(args.envPolicy),
      codexHome: getManagedCodexHome(),
      version: installation.version,
      platform: platform ?? undefined,
    };
  }

  return {
    source: 'system-cli',
    commandPath: resolveCommand('codex'),
    env: augmentedProcessEnv(args.envPolicy),
  };
}

export function isManagedCodexRuntimeInstalled(): boolean {
  if (!existsSync(getManagedCodexRuntimeRoot())) return false;
  try {
    resolveManagedCodexCommandPath();
    return true;
  } catch {
    return false;
  }
}
